---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: example
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: app
        image: eu.gcr.io/utilities-212509/gitops-poc/pfa-auth:latest
